### ISSUE TITLE
Use mono_repo to create CI for packages within this repo 

### ISSUE THREAD

**Issue by nickmeinhold** [enspyrco/the_process#45]
`dart analyze .` was erroring with lots of `uri_does_not_exist` from `microservices/create_section/...` 
  - so  I removed the step for now 

I imagine the CI could include a step to change the working directory 

```yaml
- name: Get dependencies
  working-directory: ./microservices/create_section
  run: flutter pub get
```

But a better option I think is to use mono_repo: 

[mono_repo](https://pub.dev/packages/mono_repo)
